---

- name: "MEDIUM | RHEL-09-672010 | PATCH | RHEL 9 must have the crypto-policies package installed."
  when:
    - rhel_09_672010
    - "'crypto-policies' not in ansible_facts.packages"
  tags:
    - RHEL-09-672010
    - CAT2
    - CCI-002450
    - CCI-002890
    - CCI-003123
    - SRG-OS-000396-GPOS-00176
    - SRG-OS-000393-GPOS-00173
    - SRG-OS-000394-GPOS-00174
    - SV-258234r987791_rule
    - V-258234
    - NIST800-53R4_SC-12
    - NIST800-53R4_MA-4
    - crypto
  ansible.builtin.package:
    name: crypto-policies
    state: present

- name: "MEDIUM | RHEL-09-672020 | PATCH | RHEL 9 crypto policy must not be overridden."
  when:
    - rhel_09_672020
  tags:
    - RHEL-09-672020
    - CAT2
    - CCI-002450
    - CCI-002890
    - CCI-003123
    - SRG-OS-000396-GPOS-00176
    - SRG-OS-000393-GPOS-00173
    - SRG-OS-000394-GPOS-00174
    - SV-258236r987791_rule
    - V-258236
    - NIST800-53R4_SC-12
    - NIST800-53R4_MA-4
    - crypto
  vars:
    warn_control_id: "MEDIUM | RHEL-09-672020"
  block:
    - name: "MEDIUM | RHEL-09-672020 | AUDIT | RHEL 9 crypto policy must not be overridden."
      ansible.builtin.shell: ls -l /etc/crypto-policies/back-ends/ | grep -v FIPS
      changed_when: false
      failed_when: rhel9stig_crypto_policies_fips.rc not in [ 0, 1 ]
      register: rhel9stig_crypto_policies_fips

    - name: "MEDIUM | RHEL-09-672020 | WARN | RHEL 9 crypto policy must not be overridden."
      when:
        - rhel9stig_crypto_policies_fips is defined
        - rhel9stig_crypto_policies_fips.stdout | length > 0
      ansible.builtin.debug:
        msg: "Warning!! Please Investigate 672020 - Crypto files not pointing to FIPS"

    - name: "MEDIUM | RHEL-09-672020 | WARN | RHEL 9 crypto policy must not be overridden."
      when:
        - rhel9stig_crypto_policies_fips is defined
        - rhel9stig_crypto_policies_fips.stdout | length > 0
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: "MEDIUM | RHEL-09-672025 | PATCH | RHEL 9 must use mechanisms meeting the requirements of applicable federal laws, executive orders, directives, policies, regulations, standards, and guidance for authentication to a cryptographic module."
  when:
    - rhel_09_672025
  tags:
    - RHEL-09-672025
    - CAT2
    - CCI-000803
    - SRG-OS-000120-GPOS-00061
    - SV-258237r971535_rule
    - V-258237
    - NIST800-53R4_IA-7
    - crypto
  vars:
    warn_control_id: "MEDIUM | RHEL-09-672025"
  block:
    - name: "MEDIUM | RHEL-09-672025 | AUDIT | RHEL 9 must use mechanisms meeting the requirements of applicable federal laws, executive orders, directives, policies, regulations, standards, and guidance for authentication to a cryptographic module."
      ansible.builtin.shell: file /etc/crypto-policies/back-ends/krb5.config
      changed_when: false
      failed_when: rhel9stig_crypto_krb5_fips.rc not in [ 0, 1 ]
      register: rhel9stig_crypto_krb5_fips

    - name: "MEDIUM | RHEL-09-672025 | WARN | RHEL 9 must use mechanisms meeting the requirements of applicable federal laws, executive orders, directives, policies, regulations, standards, and guidance for authentication to a cryptographic module."
      when:
        - rhel9stig_crypto_krb5_fips is defined
        - "'FIPS/krb5.txt' not in rhel9stig_crypto_krb5_fips.stdout"
      ansible.builtin.debug:
        msg: "Warning!! Please Investigate 672025 - kerberos is not FIPS compliant"

    - name: "MEDIUM | RHEL-09-672025 | WARN | RHEL 9 must use mechanisms meeting the requirements of applicable federal laws, executive orders, directives, policies, regulations, standards, and guidance for authentication to a cryptographic module."
      when:
        - rhel9stig_crypto_krb5_fips is defined
        - "'FIPS/krb5.txt' not in rhel9stig_crypto_krb5_fips.stdout"
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: "MEDIUM | RHEL-09-672035 | PATCH | RHEL 9 must implement DOD-approved encryption in the OpenSSL package."
  when:
    - rhel_09_672035
  tags:
    - RHEL-09-672035
    - CAT2
    - CCI-001453
    - SRG-OS-000250-GPOS-00093
    - SV-258239r991554_rule
    - V-258239
    - NIST800-53R4_AC-17
    - ssl
  notify: Change_requires_reboot
  ansible.builtin.lineinfile:
    path: /etc/pki/tls/openssl.cnf
    regexp: ^(|\s*)\.include = /etc/crypto-policies
    line: '.include = /etc/crypto-policies/back-ends/opensslcnf.config'

- name: "MEDIUM | RHEL-09-672040 | PATCH | RHEL 9 must implement DOD-approved TLS encryption in the OpenSSL package."
  when:
    - rhel_09_672040
  tags:
    - RHEL-09-672040
    - CAT2
    - CCI-001453
    - SRG-OS-000250-GPOS-00093
    - SV-258240r991554_rule
    - V-258240
    - NIST800-53R4_AC-17
    - ssl
  notify: Change_requires_reboot
  ansible.builtin.lineinfile:
    path: /etc/crypto-policies/back-ends/opensslcnf.config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - {line: 'TLS.MinProtocol = TLSv1.2', regexp: '^(\s*|#)TLS.MinProtocol = '}
    - {line: 'DTLS.MinProtocol = DTLSv1.2', regexp: '^(\s*|#)DTLS.MinProtocol = '}

- name: "MEDIUM | RHEL-09-672045 | PATCH | RHEL 9 must implement a system-wide encryption policy."
  when:
    - rhel_09_672045
  tags:
    - RHEL-09-672045
    - CAT2
    - CCI-002450
    - CCI-002890
    - CCI-003123
    - SRG-OS-000396-GPOS-00176
    - SRG-OS-000393-GPOS-00173
    - SRG-OS-000394-GPOS-00174
    - SV-258241r987791_rule
    - V-258241
    - NIST800-53R4_SC-3
    - NIST800-53R4_MA-4
    - fips
    - encryption
  notify: Change_requires_reboot
  vars:
    warn_control_id: "MEDIUM | RHEL-09-672045"
  block:
    - name: "MEDIUM | RHEL-09-672045 | AUDIT | RHEL 9 must implement a system-wide encryption policy."
      ansible.builtin.shell: update-crypto-policies --check
      changed_when: false
      failed_when: crypto_policies_check.rc not in [0 , 1]
      register: crypto_policies_check

    - name: "MEDIUM | RHEL-09-672045 | PATCH | RHEL 9 must implement a system-wide encryption policy."
      when:
        - "'FIPS' not in crypto_policies_check.stdout"
        - rhel9stig_disruption_high
      ansible.builtin.shell: fips-mode-setup --set FIPS

    - name: "MEDIUM | RHEL-09-672045 | WARN | RHEL 9 must implement a system-wide encryption policy."
      when:
        - "'FIPS' not in crypto_policies_check.stdout"
        - not rhel9stig_disruption_high
      ansible.builtin.debug:
        msg: WARNING!! - Crypto-Policies is not set to FIPS

    - name: "MEDIUM | RHEL-09-672045 | WARN | RHEL 9 must implement a system-wide encryption policy."
      when:
        - "'FIPS' not in crypto_policies_check.stdout"
        - not rhel9stig_disruption_high
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: "MEDIUM | RHEL-09-672050 | PATCH | RHEL 9 must implement DOD-approved encryption in the bind package."
  when:
    - rhel_09_672050
    - "'bind' in ansible_facts.packages"
  tags:
    - RHEL-09-672050
    - CAT2
    - CCI-002418
    - CCI-002422
    - SRG-OS-000423-GPOS-00187
    - SRG-OS-000426-GPOS-00190
    - SV-258242r958908_rule
    - V-258242
    - NIST800-53R4_SC-8
    - bind
    - encryption
  ansible.builtin.lineinfile:
    path: /etc/named.conf
    regexp: ^(|\s*)include = /etc/crypto-policies
    line: 'include "/etc/crypto-policies/back-ends/bind.config";'
