---

- name: "MEDIUM | RHEL-09-433010 | PATCH | RHEL 9 fapolicy module must be installed."
  when:
    - rhel_09_433010
  tags:
    - RHEL-09-433010
    - CAT2
    - CCI-01764
    - CCI-01774
    - SRG-OS-000370-GPOS-00155
    - SRG-OS-000368-GPOS-00154
    - SV-258089r958808_rule
    - V-258089
    - NIST800-53R4_IA-11
    - NIST800-53R4_AC-3
  ansible.builtin.package:
    name: fapolicyd
    state: present

- name: "MEDIUM | RHEL-09-433015 | PATCH | RHEL 9 fapolicy module must be enabled."
  when:
    - rhel_09_433015
  tags:
    - RHEL-09-433015
    - CAT2
    - CCI-01764
    - CCI-01774
    - SRG-OS-000370-GPOS-00155
    - SRG-OS-000368-GPOS-00154
    - SV-258090r958808_rule
    - V-258089
    - NIST800-53R4_IA-11
    - NIST800-53R4_AC-3
  ansible.builtin.systemd:
    enabled: true
    name: fapolicyd
    state: started
