---

- name: "MEDIUM | RHEL-09-652010 | PATCH | RHEL 9 must have the rsyslog package installed."
  when: rhel_09_652010
  tags:
    - RHEL-09-652010
    - CAT2
    - CCI-000154
    - CCI-000366
    - CCI-001851
    - SRG-OS-000479-GPOS-00224
    - SRG-OS-000051-GPOS-00024
    - SRG-OS-000480-GPOS-00227
    - SV-258140r959008_rule
    - V-258140
    - NIST800-53R4_AU-4
    - NIST800-53R4_AU-6
    - NIST800-53R4_CM-6
    - rsyslog
  ansible.builtin.package:
    name: rsyslog
    state: present

- name: "MEDIUM | RHEL-09-652015 | PATCH | RHEL 9 must have the packages required for encrypting offloaded audit logs installed."
  when: rhel_09_652015
  tags:
    - RHEL-09-652015
    - CAT2
    - CCI-000366
    - CCI-000803
    - SRG-OS-000480-GPOS-00227
    - SRG-OS-000120-GPOS-00061
    - SV-258141r991589_rule
    - V-258141
    - NIST800-53R4_IA-7
    - NIST800-53R4_CM-6
    - rsyslog
  ansible.builtin.package:
    name: rsyslog-gnutls
    state: present

- name: "MEDIUM | RHEL-09-652020 | PATCH | The rsyslog service on RHEL 9 must be active."
  when: rhel_09_652020
  tags:
    - RHEL-09-652020
    - CAT2
    - CCI-000366
    - SRG-OS-000480-GPOS-00227
    - SV-258142r991589_rule
    - V-258142
    - NIST800-53R4_CM-6
    - rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: started
    enabled: true

- name: "MEDIUM | RHEL-09-652025 | PATCH | RHEL 9 must be configured so that the rsyslog daemon does not accept log messages from other servers unless the server is being used for log aggregation."
  when:
    - rhel_09_652025
    - not rhel9stig_rsyslog_server
  tags:
    - RHEL-09-652025
    - CAT2
    - CCI-000366
    - SRG-OS-000480-GPOS-00227
    - SV-258143r991589_rule
    - V-258143
    - NIST800-53R4_CM-6
    - rsyslog
  notify: Restart_rsyslog
  block:
    - name: "MEDIUM | RHEL-09-652025 | AUDIT | RHEL 9 must be configured so that the rsyslog daemon does not accept log messages from other servers unless the server is being used for log aggregation."
      ansible.builtin.find:
        paths: /etc/rsyslog.d/
      register: rhel9stig_rsyslog_conf

    - name: "MEDIUM | RHEL-09-652025 | PATCH | RHEL 9 must be configured so that the rsyslog daemon does not accept log messages from other servers unless the server is being used for log aggregation."
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.conf
        line: '#\1\2\3'
        regex: (Input|ModLoad)(TCP|UDP|RELP|imtcp|imudp|imrelp)(.*)
        backrefs: true

    - name: "MEDIUM | RHEL-09-652025 | PATCH | RHEL 9 must be configured so that the rsyslog daemon does not accept log messages from other servers unless the server is being used for log aggregation."
      when: rhel9stig_rsyslog_conf.matched > 1
      ansible.builtin.lineinfile:
        path: "{{ item.path }}"
        line: '#\1\2\3'
        regex: (Input|ModLoad)(TCP|UDP|RELP|imtcp|imudp|imrelp)(.*)
        backrefs: true
      loop: "{{ rhel9stig_rsyslog_conf.files }}"

- name: "MEDIUM | RHEL-09-652030 | PATCH | All RHEL 9 remote access methods must be monitored."
  when: rhel_09_652030
  tags:
    - RHEL-09-652030
    - CAT2
    - CCI-000067
    - SRG-OS-000032-GPOS-00013
    - SV-258144r958406_rule
    - V-258144
    - NIST800-53R4_AC-17
    - rsyslog
  notify: Restart_rsyslog
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    line: 'auth.*;authpriv.*;daemon.* /var/log/secure'

## Required for 652035 to run
- name: "MEDIUM | RHEL-09-653130 | PATCH | RHEL 9 audispd-plugins package must be installed"
  when: rhel_09_653130
  tags:
    - RHEL-09-653130
    - CAT2
    - CCI-001851
    - SRG-OS-000342-GPOS-00133
    - SRG-OS-000479-GPOS-00224
    - SV-258175r926512_rule
    - V-258175
    - NIST800-53R4_AU-4
    - rsyslog
    - auditd
  ansible.builtin.package:
    name: audispd-plugins
    state: present

- name: "MEDIUM | RHEL-09-652035 | PATCH | RHEL 9 must be configured to offload audit records onto a different system from the system being audited via syslog."
  when: rhel_09_652035
  tags:
    - RHEL-09-652035
    - CAT2
    - CCI-001851
    - SRG-OS-000342-GPOS-00133
    - SRG-OS-000479-GPOS-00224
    - SV-258145r958754_rule
    - V-258145
    - NIST800-53R4_AU-4
    - rsyslog
  notify: Restart_rsyslog
  ansible.builtin.lineinfile:
    path: /etc/audit/plugins.d/syslog.conf
    regexp: 'active\s*='
    line: 'active = yes'

- name: "MEDIUM | RHEL-09-652040 | AUDIT | RHEL 9 must authenticate the remote logging server for offloading audit logs via rsyslog."
  when: rhel_09_652040
  tags:
    - RHEL-09-652040
    - CAT2
    - CCI-001851
    - SRG-OS-000342-GPOS-00133
    - SRG-OS-000479-GPOS-00224
    - SV-258146r958754_rule
    - V-258146
    - NIST800-53R4_AU-4
    - rsyslog
  vars:
    warn_control_id: "MEDIUM | RHEL-09-652040"
  block:
    - name: "MEDIUM | RHEL-09-652040 | AUDIT | RHEL 9 must authenticate the remote logging server for offloading audit logs via rsyslog."
      ansible.builtin.shell: grep -i "^\$ActionSendStreamDriverAuthMode" /etc/rsyslog.conf /etc/rsyslog.d/*.conf
      changed_when: false
      failed_when: rhel9stig_rsyslog_remote_auth_x509.rc not in [ 0, 1, 2 ]
      register: rhel9stig_rsyslog_remote_auth_x509

    - name: "MEDIUM | RHEL-09-652040 | WARN | RHEL 9 must authenticate the remote logging server for offloading audit logs via rsyslog."
      when:
        - rhel9stig_rsyslog_remote_auth_x509 is defined
        - "'x509' not in rhel9stig_rsyslog_remote_auth_x509.stdout"
      ansible.builtin.debug:
        msg: "Warning!! Please ensure rule RHEL-09-652040 remote syslog control requirements are met for your environment"

    - name: "MEDIUM | RHEL-09-652040 | WARN | RHEL 9 must authenticate the remote logging server for offloading audit logs via rsyslog."
      when:
        - rhel9stig_rsyslog_remote_auth_x509 is defined
        - "'x509' not in rhel9stig_rsyslog_remote_auth_x509.stdout"
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: "MEDIUM | RHEL-09-652045 | AUDIT | RHEL 9 must encrypt the transfer of audit records offloaded onto a different system or media from the system being audited via rsyslog."
  when:
    - rhel_09_652045
    - not rhel9stig_rsyslog_server
  tags:
    - RHEL-09-652045
    - CAT2
    - CCI-001851
    - SRG-OS-000342-GPOS-00133
    - SRG-OS-000479-GPOS-00224
    - SV-258147r958754_rule
    - V-258147
    - NIST800-53R4_AU-4
    - rsyslog
  vars:
    warn_control_id: "MEDIUM | RHEL-09-652045"
  block:
    - name: "MEDIUM | RHEL-09-652045 | AUDIT | RHEL 9 must encrypt the transfer of audit records offloaded onto a different system or media from the system being audited via rsyslog."
      ansible.builtin.command: grep -i "^\$ActionSendStreamDriverMode 1" /etc/rsyslog.conf /etc/rsyslog.d/*.conf
      changed_when: false
      failed_when: rhel9stig_rsyslog_remote_stream_driver.rc not in [ 0, 1, 2 ]
      register: rhel9stig_rsyslog_remote_stream_driver

    - name: "MEDIUM | RHEL-09-652045 | WARN | RHEL 9 must encrypt the transfer of audit records offloaded onto a different system or media from the system being audited via rsyslog."
      when:
        - rhel9stig_rsyslog_remote_stream_driver is defined
        - rhel9stig_rsyslog_remote_stream_driver.rc == 2
      ansible.builtin.debug:
        msg: "Warning!! Please ensure rule RHEL-09-652045 remote syslog control requirements are met for your environment"

    - name: "MEDIUM | RHEL-09-652045 | WARN | RHEL 9 must encrypt the transfer of audit records offloaded onto a different system or media from the system being audited via rsyslog."
      when:
        - rhel9stig_rsyslog_remote_stream_driver is defined
        - rhel9stig_rsyslog_remote_stream_driver.rc == 2
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: "MEDIUM | RHEL-09-652050 | AUDIT | RHEL 9 must encrypt via the gtls driver the transfer of audit records offloaded onto a different system or media from the system being audited via rsyslog."
  when:
    - rhel_09_652050
    - not rhel9stig_rsyslog_server
  tags:
    - RHEL-09-652050
    - CAT2
    - CCI-001851
    - SRG-OS-000342-GPOS-00133
    - SRG-OS-000479-GPOS-00224
    - SV-258148r958754_rule
    - V-258148
    - NIST800-53R4_AU-4
    - rsyslog
  vars:
    warn_control_id: "MEDIUM | RHEL-09-652050"
  block:
    - name: "MEDIUM | RHEL-09-652050 | AUDIT | RHEL 9 must encrypt via the gtls driver the transfer of audit records offloaded onto a different system or media from the system being audited via rsyslog."
      ansible.builtin.shell: grep -i "^\$$DefaultNetstreamDriver" /etc/rsyslog.conf /etc/rsyslog.d/*.conf
      changed_when: false
      failed_when: rhel9stig_rsyslog_remote_netstream_driver.rc not in [ 0, 1, 2 ]
      register: rhel9stig_rsyslog_remote_netstream_driver

    - name: "MEDIUM | RHEL-09-652050 | WARN | RHEL 9 must encrypt via the gtls driver the transfer of audit records offloaded onto a different system or media from the system being audited via rsyslog."
      when:
        - rhel9stig_rsyslog_remote_netstream_driver is defined
        - "'gtls' not in rhel9stig_rsyslog_remote_netstream_driver.stdout"
      ansible.builtin.debug:
        msg: "Warning!! Please ensure rule RHEL-09-652050 remote syslog control requirements are met for your environment"

    - name: "MEDIUM | RHEL-09-652050 | WARN | RHEL 9 must encrypt via the gtls driver the transfer of audit records offloaded onto a different system or media from the system being audited via rsyslog."
      when:
        - rhel9stig_rsyslog_remote_netstream_driver is defined
        - "'gtls' not in rhel9stig_rsyslog_remote_netstream_driver.stdout"
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: "MEDIUM | RHEL-09-652055 | PATCH | RHEL 9 must be configured to forward audit records via TCP to a different system or media from the system being audited via rsyslog."
  when:
    - rhel_09_652055
    - not rhel9stig_rsyslog_server
  tags:
    - RHEL-09-652055
    - CAT2
    - CCI-000366
    - CCI-001851
    - SRG-OS-000342-GPOS-00133
    - SRG-OS-000479-GPOS-00224
    - SRG-OS-000480-GPOS-00227
    - SV-258149r959008_rule
    - V-258149
    - NIST800-53R4_AU-4
    - NIST800-53R4_CM-6
    - rsyslog
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^.*\@\@'
    line: "*.* {{ rhel9stig_remotelog_server.protocol }}{{ rhel9stig_remotelog_server.server }}:{{ rhel9stig_remotelog_server.port }}"

- name: "MEDIUM | RHEL-09-652060 | PATCH | RHEL 9 must use cron logging."
  when: rhel_09_652060
  tags:
    - RHEL-09-652060
    - CAT2
    - CCI-000366
    - SRG-OS-000480-GPOS-00227
    - SV-258150r991589_rule
    - V-258150
    - NIST800-53R4_CM-6
    - rsyslog
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    regexp: 'cron\.\*(\s+)'
    line: 'cron.*\1/var/log/cron'
    backrefs: true
    insertafter: "# Log cron stuff"
