---

- name: "MEDIUM | RHEL-09-672050 | PATCH | RHEL 9 must implement DOD-approved encryption in the bind package."
  when:
    - rhel_09_672050
    - "'bind' in ansible_facts.packages"
  tags:
    - RHEL-09-672050
    - CAT2
    - CCI-002418
    - CCI-002422
    - SRG-OS-000423-GPOS-00187
    - SRG-OS-000426-GPOS-00190
    - SV-258242r958908_rule
    - V-258242
    - NIST800-53R4_SC-8
    - bind
    - encryption
  ansible.builtin.lineinfile:
    path: /etc/named.conf
    regexp: ^(#|)\s*include "/etc/crypto-policies/back-ends/bind.config"
    line: 'include "/etc/crypto-policies/back-ends/bind.config";'
