---

- name: HIGH | RHEL-09-611025 | PATCH |  RHEL 9 must not allow blank or null passwords.
  when: rhel_09_611025
  tags:
    - RHEL-09-611025
    - CAT1
    - CCI-01084
    - CCI-02696
    - SRG-OS-000445-GPOS-00199
    - SRG-OS-000134-GPOS-00068
    - SV-258094r991589_rule
    - V-258078
    - NIST800-53R4_SC-3
    - NIST800-53R4_SI-6
    - pam
  ansible.builtin.replace:
    path: "{{ null_pass }}"
    regexp: (.*) nullok(.*)
    replace: \1\2
  loop:
    - /etc/pam.d/system-auth
    - /etc/pam.d/password-auth
  loop_control:
    loop_var: null_pass

- name: HIGH | RHEL-09-671010 | PATCH | RHEL 9 must enable FIPS mode.
  when:
    - rhel_09_671010
    - not ansible_fips
  tags:
    - RHEL-09-671010
    - CAT1
    - CCI-00068
    - CCI-00877
    - CCI-002418
    - CCI-002450
    - SRG-OS-000033-GPOS-00014
    - SRG-OS-000125-GPOS-00065
    - SRG-OS-000396-GPOS-00176
    - SRG-OS-000423-GPOS-00187
    - SRG-OS-000478-GPOS-00223
    - SV-258230r958408_rule
    - V-258230
    - NIST800-53R4_AC-17
    - NIST800-53R4_MA-4
    - NIST800-53R4_SC-8
    - NIST800-53R4_SC-13
    - fips
  vars:
    warn_control_id: "HIGH | RHEL-09-671010"
  notify: Change_requires_reboot
  block:
    - name: HIGH | RHEL-09-671010 | PATCH | RHEL 9 must enable FIPS mode.
      when: rhel9stig_disruption_high
      ansible.builtin.command: fips-mode-setup --enable
      changed_when: true

    - name: HIGH | RHEL-09-671010 | WARN | RHEL 9 must enable FIPS mode. | Give Warning
      when: not rhel9stig_disruption_high
      ansible.builtin.debug:
        msg: WARNING!! - FIPS mode not setup

    - name: HIGH | RHEL-09-671010 | WARN | RHEL 9 must enable FIPS mode. | Warning Count
      when: not rhel9stig_disruption_high
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: HIGH | RHEL-09-672015 | RHEL 9 crypto policy files must match files shipped with the operating system.
  when:
    - rhel_09_672015
    - "'crypto-policies' in ansible_facts.packages"
  tags:
    - RHEL-09-672015
    - CAT1
    - CCI-02450
    - SRG-OS-000478-GPOS-00223
    - SRG-OS-000396-GPOS-00176
    - SV-258235r959006_rule
    - V-258235
    - NIST800-53R4_SC-13
    - crypto
  notify: Change_requires_reboot
  block:
    - name: HIGH | RHEL-09-672015 | AUDIT | RHEL 9 crypto policy files must match files shipped with the operating system. | Capture state
      ansible.builtin.command: rpm -V crypto-policies  # noqa: command-instead-of-module
      changed_when: false
      failed_when: crypto_policies_modified.rc not in [ 0, 1 ]
      register: crypto_policies_modified

    - name: HIGH | RHEL-09-672015 | AUDIT | RHEL 9 crypto policy files must match files shipped with the operating system. | Reinstall crypto-policies if modified
      when: crypto_policies_modified.stdout | length > 0
      ansible.builtin.command: dnf reinstall -y crypto-policies
      changed_when: true

- name: HIGH | RHEL-09-672030 | RHEL 9 must implement DOD-approved TLS encryption in the GnuTLS package.
  when:
    - rhel_09_672030
    - not ansible_facts.fips
  tags:
    - RHEL-09-672030
    - CAT1
    - CCI-001453
    - CCI-002418
    - SRG-OS-000250-GPOS-00093
    - SRG-OS-000423-GPOS-00187
    - SV-258238r991554_rule
    - V-258238
    - NIST800-53R4_AC-17
    - NIST800-53R4_SC-8
    - crypto
  vars:
    warn_control_id: "HIGH | RHEL-09-672030"
  notify: Change_requires_reboot
  block:
    - name: HIGH | RHEL-09-672030 | AUDIT | RHEL 9 must implement DOD-approved TLS encryption in the GnuTLS package. | Capture crypto state
      ansible.builtin.command: update-crypto-policies --show
      changed_when: false
      register: crypto_policies_state

    - name: HIGH | RHEL-09-672030 | PATCH | RHEL 9 must implement DOD-approved TLS encryption in the GnuTLS package. | Enable FIPS
      when:
        - not "'FIPS' in crypto_policies_state.stdout"
        - rhel9stig_disruption_high
      ansible.builtin.command: fips-mode-setup --enable
      changed_when: true

    - name: HIGH | RHEL-09-672030 | WARN | RHEL 9 must implement DOD-approved TLS encryption in the GnuTLS package. | Give Warning
      when:
        - not "'FIPS' in crypto_policies_state.stdout"
        - not rhel9stig_disruption_high
      ansible.builtin.debug:
        msg: WARNING!! - Crypto-Policies is not set to FIPS

    - name: HIGH | RHEL-09-672030 | WARN | RHEL 9 must implement DOD-approved TLS encryption in the GnuTLS package. | Warning Count
      when:
        - not "'FIPS' in crypto_policies_state.stdout"
        - not rhel9stig_disruption_high
      ansible.builtin.import_tasks:
        file: warning_facts.yml
